export const mockTopics = [
  {
    _id: "topic_1",
    topic_name: "Arrays and Strings",
    description: "Learn fundamental data structures",
    lo: "Understand array manipulation and string operations",
    order_index: 1,
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  },
  {
    _id: "topic_2",
    topic_name: "Linked Lists",
    description: "Master linked list operations",
    lo: "Implement and manipulate linked lists",
    order_index: 2,
    created_at: new Date("2024-01-02").toISOString(),
    updated_at: new Date("2024-01-02").toISOString(),
  },
];

export const mockSubTopics = [
  {
    _id: "subtopic_1",
    topic_id: "topic_1",
    sub_topic_name: "Array Traversal",
    description: "Learn to iterate through arrays",
    lo: "Master different array iteration techniques",
    order_index: 1,
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  },
  {
    _id: "subtopic_2",
    topic_id: "topic_1",
    sub_topic_name: "String Manipulation",
    description: "Work with string methods",
    lo: "Understand string operations",
    order_index: 2,
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  },
];

export const mockProblems = [
  {
    _id: "problem_1",
    topic_id: "topic_1",
    sub_topic_id: "subtopic_1",
    name: "Two Sum",
    description: "Find two numbers that add up to a target",
    difficulty: 1,
    code_template: "function twoSum(nums, target) {\n  // Your code here\n}",
    guidelines: "Use hash map for O(n) solution",
    solution: "Hash map approach",
    time_limit_ms: 1000,
    memory_limit_mb: 512,
    number_of_tests: 5,
    is_public: true,
    is_active: true,
    sets: "basic,interview",
    steps: "1. Create hash map\n2. Iterate array\n3. Check complement",
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  },
  {
    _id: "problem_2",
    topic_id: "topic_1",
    sub_topic_id: "subtopic_2",
    name: "Reverse String",
    description: "Reverse a string in-place",
    difficulty: 1,
    code_template: "function reverseString(s) {\n  // Your code here\n}",
    guidelines: "Use two pointers",
    solution: "Two pointer approach",
    time_limit_ms: 1000,
    memory_limit_mb: 256,
    number_of_tests: 3,
    is_public: true,
    is_active: true,
    sets: "basic",
    steps: "1. Use two pointers\n2. Swap characters",
    created_at: new Date("2024-01-02").toISOString(),
    updated_at: new Date("2024-01-02").toISOString(),
  },
];

export const mockTestCases = [
  {
    _id: "test_1",
    problem_id: "problem_1",
    input_data: "[2,7,11,15], 9",
    expected_output: "[0,1]",
    is_public: true,
    order_index: 1,
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  },
  {
    _id: "test_2",
    problem_id: "problem_1",
    input_data: "[3,2,4], 6",
    expected_output: "[1,2]",
    is_public: true,
    order_index: 2,
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  },
];
